Repository bcgov/smk-clean-bc, pull requests merged in 2022-11, with the labels that each got.

#4 Add GitHub Actions and OpenShift files
  .github/workflows/build-deploy-dev.yaml
  .github/workflows/deploy_prod.yaml
  Dockerfile
  code_of_conduct.md
  openshift/README.md
  openshift/smk-template.yaml
Labels: 20221109-2123

#7 Update Dockerfile to include missing files
  Dockerfile
Labels: 20221109-2154

#20 Use config map for route planner api key
  .github/workflows/build-deploy-dev.yaml
  .github/workflows/deploy_prod.yaml
  config/route-planner.json
  print-directions-portrait.html
  smk-config.json
  smk-init.js
Labels: 20221110-2242

#22 Print directions template updated
  assets/BCID_H_rgb_pos.png
  assets/CleanBC_logo.svg
  print-directions-portrait.html
Labels: 20221117-2245

#23 Disclaimer panel
  assets/style.css
  dialog-polyfill/dialog-polyfill.css
  dialog-polyfill/dialog-polyfill.js
  disclaimer.html
  index.html
  smk-init.js
Labels: 20221123-1818

#24 Dialog files moved into assets dir
  assets/dialog-polyfill/dialog-polyfill.css
  assets/dialog-polyfill/dialog-polyfill.js
  assets/disclaimer.html
  index.html
  smk-init.js
Labels: 20221123-1838
