Repository bcgov/smk-clean-bc, pull requests merged in 2023-02, with the labels that each got.

#78 Temporarily remove BC restriction
  smk-config.json
Labels: 20230206-1955

#79 Consume SMK 1.1.5
  package-lock.json
  package.json
  smk-config.json
Labels: 20230206-2125

#82 Condensed mobile header
  assets/style.css
  index.html
Labels: 20230213-2015

#83 Ministry EVCS layer uses conditional styling
  package-lock.json
  package.json
  smk-config.json
Labels: 20230215-0000

#94 Change Charging Stations layer from Esri Feature to GeoJSON
  layers/-smk-catalog.json
  smk-config.json
Labels: 20230223-2347
